# Generated by Django 3.2.8 on 2021-10-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of Business'),
        ),
    ]
