# Generated by Django 3.2.8 on 2021-10-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_investorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smeprofile',
            old_name='nin',
            new_name='tin',
        ),
    ]
