# Generated by Django 3.2.8 on 2021-10-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='date_paid',
            field=models.DateTimeField(null=True),
        ),
    ]
